In [3]:
import math
import numpy as np

def sigmoid(x):
    return 1 / (1 + math.exp(-x))

In [ ]:
x = 0.5
y = 0
z = 5

Wxa= 1
Wya = 2
Wyb = 1
Wzc = 0.2
Wad = 1
WBd = 1.5
Wcd = -1

In [4]:
xyz = np.array([0.5, 0.0, 5.0])

In [5]:
xyz

array([0.5, 0. , 5. ])

In [7]:
W = np.array([[2.0, 0.0, 0.0],
              [2.0, 1.0, 0.0],
              [0.0, 0.0, 0.2]])

In [12]:
xyz * W

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [11]:
np.transpose(xyz) * W

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])