In [1]:
import re
from collections import namedtuple, Counter

with open('../input/emoji-data-descriptions-codepoints/emoji-test.txt', 'rt') as file:
    emoji_raw = file.read()
    

FileNotFoundError: [Errno 2] No such file or directory: '../input/emoji-data-descriptions-codepoints/emoji-test.txt'

In [3]:
print(emoji_raw[:2800])

In [ ]:
x = 0.5
y = 0
z = 5

Wxa= 1
Wya = 2
Wyb = 1
Wzc = 0.2
Wad = 1
WBd = 1.5
Wcd = -1

In [4]:
xyz = np.array([0.5, 0.0, 5.0])

In [5]:
xyz

array([0.5, 0. , 5. ])

In [7]:
W = np.array([[2.0, 0.0, 0.0],
              [2.0, 1.0, 0.0],
              [0.0, 0.0, 0.2]])

In [12]:
xyz * W

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [11]:
np.transpose(xyz) * W

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])